### ISSUE TITLE
Classifier ouput features are 4 in Model, then why this printed as 1?

### ISSUE THREAD

**Issue by shivanandmn** [abhimishra91/transformers-tutorials#12]
https://github.com/abhimishra91/transformers-tutorials/blob/9f1283418bd8cfe431e12df8349468ddd53b86f9/transformers_multiclass_classification.ipynb#L527

**Comment by abhimishra91** [comment]
Hi @Shivanandmn, thank you for pointing that out. The prompt output is from my previous model that had only 1 neuron in the final layer. 

That should be 4 for the current network. However, there is no change in the model performance for this particular dataset. I will re-run the notebook and update it with the correct prompts. Rest assured you can take the notebook as it is and execute.
